// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlcdb

import (
	"database/sql"
	"time"
)

type GroupMember struct {
	ID                int64          `db:"id" json:"id"`
	Title             string         `db:"title" json:"title"`
	LoginName         string         `db:"login_name" json:"login_name"`
	Email             sql.NullString `db:"email" json:"email"`
	PrincipalType     int64          `db:"principal_type" json:"principal_type"`
	UserPrincipalName sql.NullString `db:"user_principal_name" json:"user_principal_name"`
	GroupID           int64          `db:"group_id" json:"group_id"`
	SiteID            string         `db:"site_id" json:"site_id"`
	Updated           string         `db:"updated" json:"updated"`
	CreatedAt         time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt         time.Time      `db:"updated_at" json:"updated_at"`
}

type RunStatus struct {
	ID                  int64     `db:"id" json:"id"`
	FullExportCompleted bool      `db:"full_export_completed" json:"full_export_completed"`
	CreatedAt           time.Time `db:"created_at" json:"created_at"`
	UpdatedAt           time.Time `db:"updated_at" json:"updated_at"`
}

type Site struct {
	SiteID         string          `db:"site_id" json:"site_id"`
	SiteUrl        string          `db:"site_url" json:"site_url"`
	TimeCreated    sql.NullString  `db:"time_created" json:"time_created"`
	Modified       sql.NullString  `db:"modified" json:"modified"`
	Title          sql.NullString  `db:"title" json:"title"`
	TemplateName   sql.NullString  `db:"template_name" json:"template_name"`
	CreatedByEmail sql.NullString  `db:"created_by_email" json:"created_by_email"`
	GroupID        sql.NullString  `db:"group_id" json:"group_id"`
	LastActivityOn sql.NullString  `db:"last_activity_on" json:"last_activity_on"`
	StorageUsed    sql.NullFloat64 `db:"storage_used" json:"storage_used"`
	LockState      sql.NullString  `db:"lock_state" json:"lock_state"`
	CreatedAt      time.Time       `db:"created_at" json:"created_at"`
	UpdatedAt      time.Time       `db:"updated_at" json:"updated_at"`
}

type SiteGroup struct {
	ID          int64          `db:"id" json:"id"`
	Title       string         `db:"title" json:"title"`
	LoginName   string         `db:"login_name" json:"login_name"`
	Description sql.NullString `db:"description" json:"description"`
	OwnerTitle  sql.NullString `db:"owner_title" json:"owner_title"`
	SiteID      string         `db:"site_id" json:"site_id"`
	Updated     string         `db:"updated" json:"updated"`
	CreatedAt   time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt   time.Time      `db:"updated_at" json:"updated_at"`
}

type SiteUser struct {
	ID                             sql.NullInt64  `db:"id" json:"id"`
	SiteID                         sql.NullString `db:"site_id" json:"site_id"`
	Email                          sql.NullString `db:"email" json:"email"`
	Expiration                     sql.NullString `db:"expiration" json:"expiration"`
	IsEmailAuthenticationGuestUser sql.NullBool   `db:"is_email_authentication_guest_user" json:"is_email_authentication_guest_user"`
	IsHiddenInUi                   sql.NullBool   `db:"is_hidden_in_ui" json:"is_hidden_in_ui"`
	IsShareByEmailGuestUser        sql.NullBool   `db:"is_share_by_email_guest_user" json:"is_share_by_email_guest_user"`
	IsSiteAdmin                    sql.NullBool   `db:"is_site_admin" json:"is_site_admin"`
	LoginName                      sql.NullString `db:"login_name" json:"login_name"`
	PrincipalType                  sql.NullInt64  `db:"principal_type" json:"principal_type"`
	Title                          sql.NullString `db:"title" json:"title"`
	UseridNameID                   sql.NullString `db:"userid_name_id" json:"userid_name_id"`
	UseridNameIDIssuer             sql.NullString `db:"userid_name_id_issuer" json:"userid_name_id_issuer"`
	UserPrincipalName              sql.NullString `db:"user_principal_name" json:"user_principal_name"`
	Updated                        sql.NullString `db:"updated" json:"updated"`
	CreatedAt                      time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt                      time.Time      `db:"updated_at" json:"updated_at"`
}

type UserProfile struct {
	PersonalUrl                    string         `db:"personal_url" json:"personal_url"`
	DocID                          sql.NullString `db:"doc_id" json:"doc_id"`
	AadObjectID                    sql.NullString `db:"aad_object_id" json:"aad_object_id"`
	AccountName                    sql.NullString `db:"account_name" json:"account_name"`
	PersonalSiteInstantiationState sql.NullString `db:"personal_site_instantiation_state" json:"personal_site_instantiation_state"`
	ProfileSid                     sql.NullString `db:"profile_sid" json:"profile_sid"`
	UserProfileGuid                sql.NullString `db:"user_profile_guid" json:"user_profile_guid"`
	UserPrincipalName              sql.NullString `db:"user_principal_name" json:"user_principal_name"`
	LastModifiedTime               sql.NullString `db:"last_modified_time" json:"last_modified_time"`
	CreatedAt                      time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt                      time.Time      `db:"updated_at" json:"updated_at"`
}
