// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: run_status.sql

package sqlcdb

import (
	"context"
)

const createRunStatus = `-- name: CreateRunStatus :exec
INSERT INTO run_status (id, full_export_completed)
VALUES (?, ?)
`

type CreateRunStatusParams struct {
	ID                  int64 `db:"id" json:"id"`
	FullExportCompleted bool  `db:"full_export_completed" json:"full_export_completed"`
}

func (q *Queries) CreateRunStatus(ctx context.Context, arg CreateRunStatusParams) error {
	_, err := q.db.ExecContext(ctx, createRunStatus, arg.ID, arg.FullExportCompleted)
	return err
}

const getRunStatus = `-- name: GetRunStatus :one
SELECT id, full_export_completed
FROM run_status 
WHERE id = ?
`

type GetRunStatusRow struct {
	ID                  int64 `db:"id" json:"id"`
	FullExportCompleted bool  `db:"full_export_completed" json:"full_export_completed"`
}

func (q *Queries) GetRunStatus(ctx context.Context, id int64) (GetRunStatusRow, error) {
	row := q.db.QueryRowContext(ctx, getRunStatus, id)
	var i GetRunStatusRow
	err := row.Scan(&i.ID, &i.FullExportCompleted)
	return i, err
}

const updateRunStatus = `-- name: UpdateRunStatus :exec
UPDATE run_status 
SET full_export_completed = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateRunStatusParams struct {
	FullExportCompleted bool  `db:"full_export_completed" json:"full_export_completed"`
	ID                  int64 `db:"id" json:"id"`
}

func (q *Queries) UpdateRunStatus(ctx context.Context, arg UpdateRunStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateRunStatus, arg.FullExportCompleted, arg.ID)
	return err
}
