// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: site_users.sql

package sqlcdb

import (
	"context"
	"database/sql"
)

const insertSiteUser = `-- name: InsertSiteUser :exec
INSERT INTO site_users (
    id, site_id, email, expiration, is_email_authentication_guest_user,
    is_hidden_in_ui, is_share_by_email_guest_user, is_site_admin,
    login_name, principal_type, title, userid_name_id, userid_name_id_issuer,
    user_principal_name, updated
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertSiteUserParams struct {
	ID                             sql.NullInt64  `db:"id" json:"id"`
	SiteID                         sql.NullString `db:"site_id" json:"site_id"`
	Email                          sql.NullString `db:"email" json:"email"`
	Expiration                     sql.NullString `db:"expiration" json:"expiration"`
	IsEmailAuthenticationGuestUser sql.NullBool   `db:"is_email_authentication_guest_user" json:"is_email_authentication_guest_user"`
	IsHiddenInUi                   sql.NullBool   `db:"is_hidden_in_ui" json:"is_hidden_in_ui"`
	IsShareByEmailGuestUser        sql.NullBool   `db:"is_share_by_email_guest_user" json:"is_share_by_email_guest_user"`
	IsSiteAdmin                    sql.NullBool   `db:"is_site_admin" json:"is_site_admin"`
	LoginName                      sql.NullString `db:"login_name" json:"login_name"`
	PrincipalType                  sql.NullInt64  `db:"principal_type" json:"principal_type"`
	Title                          sql.NullString `db:"title" json:"title"`
	UseridNameID                   sql.NullString `db:"userid_name_id" json:"userid_name_id"`
	UseridNameIDIssuer             sql.NullString `db:"userid_name_id_issuer" json:"userid_name_id_issuer"`
	UserPrincipalName              sql.NullString `db:"user_principal_name" json:"user_principal_name"`
	Updated                        sql.NullString `db:"updated" json:"updated"`
}

func (q *Queries) InsertSiteUser(ctx context.Context, arg InsertSiteUserParams) error {
	_, err := q.db.ExecContext(ctx, insertSiteUser,
		arg.ID,
		arg.SiteID,
		arg.Email,
		arg.Expiration,
		arg.IsEmailAuthenticationGuestUser,
		arg.IsHiddenInUi,
		arg.IsShareByEmailGuestUser,
		arg.IsSiteAdmin,
		arg.LoginName,
		arg.PrincipalType,
		arg.Title,
		arg.UseridNameID,
		arg.UseridNameIDIssuer,
		arg.UserPrincipalName,
		arg.Updated,
	)
	return err
}

const upsertSiteUser = `-- name: UpsertSiteUser :exec
INSERT INTO site_users (
    id, site_id, email, expiration, is_email_authentication_guest_user,
    is_hidden_in_ui, is_share_by_email_guest_user, is_site_admin,
    login_name, principal_type, title, userid_name_id, userid_name_id_issuer,
    user_principal_name, updated
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(id, site_id) DO UPDATE SET
    email = excluded.email,
    expiration = excluded.expiration,
    is_email_authentication_guest_user = excluded.is_email_authentication_guest_user,
    is_hidden_in_ui = excluded.is_hidden_in_ui,
    is_share_by_email_guest_user = excluded.is_share_by_email_guest_user,
    is_site_admin = excluded.is_site_admin,
    login_name = excluded.login_name,
    principal_type = excluded.principal_type,
    title = excluded.title,
    userid_name_id = excluded.userid_name_id,
    userid_name_id_issuer = excluded.userid_name_id_issuer,
    user_principal_name = excluded.user_principal_name,
    updated = excluded.updated,
    updated_at = CURRENT_TIMESTAMP
`

type UpsertSiteUserParams struct {
	ID                             sql.NullInt64  `db:"id" json:"id"`
	SiteID                         sql.NullString `db:"site_id" json:"site_id"`
	Email                          sql.NullString `db:"email" json:"email"`
	Expiration                     sql.NullString `db:"expiration" json:"expiration"`
	IsEmailAuthenticationGuestUser sql.NullBool   `db:"is_email_authentication_guest_user" json:"is_email_authentication_guest_user"`
	IsHiddenInUi                   sql.NullBool   `db:"is_hidden_in_ui" json:"is_hidden_in_ui"`
	IsShareByEmailGuestUser        sql.NullBool   `db:"is_share_by_email_guest_user" json:"is_share_by_email_guest_user"`
	IsSiteAdmin                    sql.NullBool   `db:"is_site_admin" json:"is_site_admin"`
	LoginName                      sql.NullString `db:"login_name" json:"login_name"`
	PrincipalType                  sql.NullInt64  `db:"principal_type" json:"principal_type"`
	Title                          sql.NullString `db:"title" json:"title"`
	UseridNameID                   sql.NullString `db:"userid_name_id" json:"userid_name_id"`
	UseridNameIDIssuer             sql.NullString `db:"userid_name_id_issuer" json:"userid_name_id_issuer"`
	UserPrincipalName              sql.NullString `db:"user_principal_name" json:"user_principal_name"`
	Updated                        sql.NullString `db:"updated" json:"updated"`
}

func (q *Queries) UpsertSiteUser(ctx context.Context, arg UpsertSiteUserParams) error {
	_, err := q.db.ExecContext(ctx, upsertSiteUser,
		arg.ID,
		arg.SiteID,
		arg.Email,
		arg.Expiration,
		arg.IsEmailAuthenticationGuestUser,
		arg.IsHiddenInUi,
		arg.IsShareByEmailGuestUser,
		arg.IsSiteAdmin,
		arg.LoginName,
		arg.PrincipalType,
		arg.Title,
		arg.UseridNameID,
		arg.UseridNameIDIssuer,
		arg.UserPrincipalName,
		arg.Updated,
	)
	return err
}
