// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: sites_select.sql

package sqlcdb

import (
	"context"
)

const getSiteCount = `-- name: GetSiteCount :one
SELECT COUNT(*) FROM sites
`

func (q *Queries) GetSiteCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getSiteCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}
