// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: site_groups.sql

package sqlcdb

import (
	"context"
	"database/sql"
)

const insertGroupMembersBatch = `-- name: InsertGroupMembersBatch :exec
INSERT INTO group_members (
    id, title, login_name, email, principal_type, user_principal_name, group_id, site_id, updated
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertGroupMembersBatchParams struct {
	ID                int64          `db:"id" json:"id"`
	Title             string         `db:"title" json:"title"`
	LoginName         string         `db:"login_name" json:"login_name"`
	Email             sql.NullString `db:"email" json:"email"`
	PrincipalType     int64          `db:"principal_type" json:"principal_type"`
	UserPrincipalName sql.NullString `db:"user_principal_name" json:"user_principal_name"`
	GroupID           int64          `db:"group_id" json:"group_id"`
	SiteID            string         `db:"site_id" json:"site_id"`
	Updated           string         `db:"updated" json:"updated"`
}

func (q *Queries) InsertGroupMembersBatch(ctx context.Context, arg InsertGroupMembersBatchParams) error {
	_, err := q.db.ExecContext(ctx, insertGroupMembersBatch,
		arg.ID,
		arg.Title,
		arg.LoginName,
		arg.Email,
		arg.PrincipalType,
		arg.UserPrincipalName,
		arg.GroupID,
		arg.SiteID,
		arg.Updated,
	)
	return err
}

const insertSiteGroupsBatch = `-- name: InsertSiteGroupsBatch :exec
INSERT INTO site_groups (
    id, title, login_name, description, owner_title, site_id, updated
) VALUES (?, ?, ?, ?, ?, ?, ?)
`

type InsertSiteGroupsBatchParams struct {
	ID          int64          `db:"id" json:"id"`
	Title       string         `db:"title" json:"title"`
	LoginName   string         `db:"login_name" json:"login_name"`
	Description sql.NullString `db:"description" json:"description"`
	OwnerTitle  sql.NullString `db:"owner_title" json:"owner_title"`
	SiteID      string         `db:"site_id" json:"site_id"`
	Updated     string         `db:"updated" json:"updated"`
}

func (q *Queries) InsertSiteGroupsBatch(ctx context.Context, arg InsertSiteGroupsBatchParams) error {
	_, err := q.db.ExecContext(ctx, insertSiteGroupsBatch,
		arg.ID,
		arg.Title,
		arg.LoginName,
		arg.Description,
		arg.OwnerTitle,
		arg.SiteID,
		arg.Updated,
	)
	return err
}

const upsertGroupMembersBatch = `-- name: UpsertGroupMembersBatch :exec
INSERT OR REPLACE INTO group_members (
    id, title, login_name, email, principal_type, user_principal_name, group_id, site_id, updated
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type UpsertGroupMembersBatchParams struct {
	ID                int64          `db:"id" json:"id"`
	Title             string         `db:"title" json:"title"`
	LoginName         string         `db:"login_name" json:"login_name"`
	Email             sql.NullString `db:"email" json:"email"`
	PrincipalType     int64          `db:"principal_type" json:"principal_type"`
	UserPrincipalName sql.NullString `db:"user_principal_name" json:"user_principal_name"`
	GroupID           int64          `db:"group_id" json:"group_id"`
	SiteID            string         `db:"site_id" json:"site_id"`
	Updated           string         `db:"updated" json:"updated"`
}

func (q *Queries) UpsertGroupMembersBatch(ctx context.Context, arg UpsertGroupMembersBatchParams) error {
	_, err := q.db.ExecContext(ctx, upsertGroupMembersBatch,
		arg.ID,
		arg.Title,
		arg.LoginName,
		arg.Email,
		arg.PrincipalType,
		arg.UserPrincipalName,
		arg.GroupID,
		arg.SiteID,
		arg.Updated,
	)
	return err
}

const upsertSiteGroupsBatch = `-- name: UpsertSiteGroupsBatch :exec
INSERT OR REPLACE INTO site_groups (
    id, title, login_name, description, owner_title, site_id, updated
) VALUES (?, ?, ?, ?, ?, ?, ?)
`

type UpsertSiteGroupsBatchParams struct {
	ID          int64          `db:"id" json:"id"`
	Title       string         `db:"title" json:"title"`
	LoginName   string         `db:"login_name" json:"login_name"`
	Description sql.NullString `db:"description" json:"description"`
	OwnerTitle  sql.NullString `db:"owner_title" json:"owner_title"`
	SiteID      string         `db:"site_id" json:"site_id"`
	Updated     string         `db:"updated" json:"updated"`
}

func (q *Queries) UpsertSiteGroupsBatch(ctx context.Context, arg UpsertSiteGroupsBatchParams) error {
	_, err := q.db.ExecContext(ctx, upsertSiteGroupsBatch,
		arg.ID,
		arg.Title,
		arg.LoginName,
		arg.Description,
		arg.OwnerTitle,
		arg.SiteID,
		arg.Updated,
	)
	return err
}
