// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: sites.sql

package sqlcdb

import (
	"context"
	"database/sql"
)

const insertSite = `-- name: InsertSite :exec
INSERT INTO sites (
    site_id, site_url, time_created, modified, title, template_name,
    created_by_email, group_id, last_activity_on, storage_used, lock_state
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertSiteParams struct {
	SiteID         string          `db:"site_id" json:"site_id"`
	SiteUrl        string          `db:"site_url" json:"site_url"`
	TimeCreated    sql.NullString  `db:"time_created" json:"time_created"`
	Modified       sql.NullString  `db:"modified" json:"modified"`
	Title          sql.NullString  `db:"title" json:"title"`
	TemplateName   sql.NullString  `db:"template_name" json:"template_name"`
	CreatedByEmail sql.NullString  `db:"created_by_email" json:"created_by_email"`
	GroupID        sql.NullString  `db:"group_id" json:"group_id"`
	LastActivityOn sql.NullString  `db:"last_activity_on" json:"last_activity_on"`
	StorageUsed    sql.NullFloat64 `db:"storage_used" json:"storage_used"`
	LockState      sql.NullString  `db:"lock_state" json:"lock_state"`
}

func (q *Queries) InsertSite(ctx context.Context, arg InsertSiteParams) error {
	_, err := q.db.ExecContext(ctx, insertSite,
		arg.SiteID,
		arg.SiteUrl,
		arg.TimeCreated,
		arg.Modified,
		arg.Title,
		arg.TemplateName,
		arg.CreatedByEmail,
		arg.GroupID,
		arg.LastActivityOn,
		arg.StorageUsed,
		arg.LockState,
	)
	return err
}

const upsertSite = `-- name: UpsertSite :exec
INSERT INTO sites (
    site_id, site_url, time_created, modified, title, template_name,
    created_by_email, group_id, last_activity_on, storage_used, lock_state
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(site_id) DO UPDATE SET
    site_url = excluded.site_url,
    time_created = excluded.time_created,
    modified = excluded.modified,
    title = excluded.title,
    template_name = excluded.template_name,
    created_by_email = excluded.created_by_email,
    group_id = excluded.group_id,
    last_activity_on = excluded.last_activity_on,
    storage_used = excluded.storage_used,
    lock_state = excluded.lock_state,
    updated_at = CURRENT_TIMESTAMP
`

type UpsertSiteParams struct {
	SiteID         string          `db:"site_id" json:"site_id"`
	SiteUrl        string          `db:"site_url" json:"site_url"`
	TimeCreated    sql.NullString  `db:"time_created" json:"time_created"`
	Modified       sql.NullString  `db:"modified" json:"modified"`
	Title          sql.NullString  `db:"title" json:"title"`
	TemplateName   sql.NullString  `db:"template_name" json:"template_name"`
	CreatedByEmail sql.NullString  `db:"created_by_email" json:"created_by_email"`
	GroupID        sql.NullString  `db:"group_id" json:"group_id"`
	LastActivityOn sql.NullString  `db:"last_activity_on" json:"last_activity_on"`
	StorageUsed    sql.NullFloat64 `db:"storage_used" json:"storage_used"`
	LockState      sql.NullString  `db:"lock_state" json:"lock_state"`
}

func (q *Queries) UpsertSite(ctx context.Context, arg UpsertSiteParams) error {
	_, err := q.db.ExecContext(ctx, upsertSite,
		arg.SiteID,
		arg.SiteUrl,
		arg.TimeCreated,
		arg.Modified,
		arg.Title,
		arg.TemplateName,
		arg.CreatedByEmail,
		arg.GroupID,
		arg.LastActivityOn,
		arg.StorageUsed,
		arg.LockState,
	)
	return err
}
