// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: user_profiles.sql

package sqlcdb

import (
	"context"
	"database/sql"
)

const insertUserProfile = `-- name: InsertUserProfile :exec
INSERT INTO user_profiles (
    personal_url, doc_id, aad_object_id, account_name,
    personal_site_instantiation_state, profile_sid, user_profile_guid,
    user_principal_name, last_modified_time
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertUserProfileParams struct {
	PersonalUrl                    string         `db:"personal_url" json:"personal_url"`
	DocID                          sql.NullString `db:"doc_id" json:"doc_id"`
	AadObjectID                    sql.NullString `db:"aad_object_id" json:"aad_object_id"`
	AccountName                    sql.NullString `db:"account_name" json:"account_name"`
	PersonalSiteInstantiationState sql.NullString `db:"personal_site_instantiation_state" json:"personal_site_instantiation_state"`
	ProfileSid                     sql.NullString `db:"profile_sid" json:"profile_sid"`
	UserProfileGuid                sql.NullString `db:"user_profile_guid" json:"user_profile_guid"`
	UserPrincipalName              sql.NullString `db:"user_principal_name" json:"user_principal_name"`
	LastModifiedTime               sql.NullString `db:"last_modified_time" json:"last_modified_time"`
}

func (q *Queries) InsertUserProfile(ctx context.Context, arg InsertUserProfileParams) error {
	_, err := q.db.ExecContext(ctx, insertUserProfile,
		arg.PersonalUrl,
		arg.DocID,
		arg.AadObjectID,
		arg.AccountName,
		arg.PersonalSiteInstantiationState,
		arg.ProfileSid,
		arg.UserProfileGuid,
		arg.UserPrincipalName,
		arg.LastModifiedTime,
	)
	return err
}

const upsertUserProfile = `-- name: UpsertUserProfile :exec
INSERT INTO user_profiles (
    personal_url, doc_id, aad_object_id, account_name,
    personal_site_instantiation_state, profile_sid, user_profile_guid,
    user_principal_name, last_modified_time
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(personal_url) DO UPDATE SET
    doc_id = excluded.doc_id,
    aad_object_id = excluded.aad_object_id,
    account_name = excluded.account_name,
    personal_site_instantiation_state = excluded.personal_site_instantiation_state,
    profile_sid = excluded.profile_sid,
    user_profile_guid = excluded.user_profile_guid,
    user_principal_name = excluded.user_principal_name,
    last_modified_time = excluded.last_modified_time,
    updated_at = CURRENT_TIMESTAMP
`

type UpsertUserProfileParams struct {
	PersonalUrl                    string         `db:"personal_url" json:"personal_url"`
	DocID                          sql.NullString `db:"doc_id" json:"doc_id"`
	AadObjectID                    sql.NullString `db:"aad_object_id" json:"aad_object_id"`
	AccountName                    sql.NullString `db:"account_name" json:"account_name"`
	PersonalSiteInstantiationState sql.NullString `db:"personal_site_instantiation_state" json:"personal_site_instantiation_state"`
	ProfileSid                     sql.NullString `db:"profile_sid" json:"profile_sid"`
	UserProfileGuid                sql.NullString `db:"user_profile_guid" json:"user_profile_guid"`
	UserPrincipalName              sql.NullString `db:"user_principal_name" json:"user_principal_name"`
	LastModifiedTime               sql.NullString `db:"last_modified_time" json:"last_modified_time"`
}

func (q *Queries) UpsertUserProfile(ctx context.Context, arg UpsertUserProfileParams) error {
	_, err := q.db.ExecContext(ctx, upsertUserProfile,
		arg.PersonalUrl,
		arg.DocID,
		arg.AadObjectID,
		arg.AccountName,
		arg.PersonalSiteInstantiationState,
		arg.ProfileSid,
		arg.UserProfileGuid,
		arg.UserPrincipalName,
		arg.LastModifiedTime,
	)
	return err
}
